// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ai/score': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ai/score.post').default>>>>
    }
    '/api/oauth/github/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/oauth/github/callback.get').default>>>>
    }
    '/api/oauth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/oauth/github/index.get').default>>>>
    }
    '/api/oauth/google/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/oauth/google/callback.get').default>>>>
    }
    '/api/oauth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/oauth/google/index.get').default>>>>
    }
    '/api/r2/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/r2/upload.post').default>>>>
    }
    '/api/team/invitation': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/team/invitation').default>>>>
    }
    '/api/trpc/:trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trpc/[trpc]').default>>>>
    }
    '/api/webhooks/chargebee': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/chargebee/index.post').default>>>>
    }
    '/api/webhooks/lemonsqueezy': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/lemonsqueezy/index.post').default>>>>
    }
    '/api/webhooks/stripe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/stripe/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/emails': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@vue-email+nuxt@0.8.19_magicast@0.3.5_typescript@5.6.3_vue@3.5.13_typescript@5.6.3_/node_modules/@vue-email/nuxt/dist/runtime/server/api/emails.get').default>>>>
    }
    '/api/render/:file': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@vue-email+nuxt@0.8.19_magicast@0.3.5_typescript@5.6.3_vue@3.5.13_typescript@5.6.3_/node_modules/@vue-email/nuxt/dist/runtime/server/api/render/[file].post').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._5kgan4cud4jbkht775nl4u6hqq/node_modules/nuxt-site-config/dist/runtime/nitro/routes/__site-config__/debug').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_xli7datkpntc2nvw6xaylodxd4/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/robots-txt').default>>>>
    }
    '/__robots__/nuxt-content.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_xli7datkpntc2nvw6xaylodxd4/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/__robots__/nuxt-content').default>>>>
    }
    '/__robots__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_xli7datkpntc2nvw6xaylodxd4/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/__robots__/debug').default>>>>
    }
    '/__robots__/debug-path.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_xli7datkpntc2nvw6xaylodxd4/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/__robots__/debug-path').default>>>>
    }
    '/__sitemap__/nuxt-content-urls.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@6.1.5_h3@1.13.0_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_t_uuqe2d5xq3ppljildmocomovsm/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/__sitemap__/nuxt-content-urls').default>>>>
    }
    '/__sitemap__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@6.1.5_h3@1.13.0_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_t_uuqe2d5xq3ppljildmocomovsm/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/__sitemap__/debug').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@6.1.5_h3@1.13.0_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_t_uuqe2d5xq3ppljildmocomovsm/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+sitemap@6.1.5_h3@1.13.0_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_t_uuqe2d5xq3ppljildmocomovsm/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xml').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0_lvglfye353ngog4vxmsitjupfu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/font').default>>>>
    }
    '/__og-image__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0_lvglfye353ngog4vxmsitjupfu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/debug.json').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0_lvglfye353ngog4vxmsitjupfu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0_lvglfye353ngog4vxmsitjupfu/node_modules/nuxt-og-image/dist/runtime/nitro/routes/image').default>>>>
    }
    '/__schema-org__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-schema-org@3.4.7_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_hmicoss56wvemrfzghdz2kdefy/node_modules/nuxt-schema-org/dist/runtime/server/routes/__schema-org__/debug').default>>>>
    }
    '/__link-checker__/inspect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-link-checker@3.1.3_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._rfyybymfu2s3p7kh2r4fc67c5i/node_modules/nuxt-link-checker/dist/runtime/nitro/routes/__link-checker__/inspect').default>>>>
    }
    '/__link-checker__/links': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-link-checker@3.1.3_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._rfyybymfu2s3p7kh2r4fc67c5i/node_modules/nuxt-link-checker/dist/runtime/nitro/routes/__link-checker__/links').default>>>>
    }
    '/__link-checker__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt-link-checker@3.1.3_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._rfyybymfu2s3p7kh2r4fc67c5i/node_modules/nuxt-link-checker/dist/runtime/nitro/routes/__link-checker__/debug').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+image@1.8.1_ioredis@5.4.1_magicast@0.3.5_rollup@4.27.3/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}