// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._5kgan4cud4jbkht775nl4u6hqq/node_modules/nuxt-site-config/dist/runtime/nuxt/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@1.6.1_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0__vue@3.5.13_typescript@5.6.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@1.6.1_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0__vue@3.5.13_typescript@5.6.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.23_h3@1.13.0_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_b75e6eragwpny22ycmvsufcmj4/node_modules/@nuxtjs/seo/dist/runtime/nuxt/plugin/titles.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.23_h3@1.13.0_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_b75e6eragwpny22ycmvsufcmj4/node_modules/@nuxtjs/seo/dist/runtime/nuxt/plugin/defaultsWaitI18n.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-link-checker@3.1.3_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._rfyybymfu2s3p7kh2r4fc67c5i/node_modules/nuxt-link-checker/dist/runtime/nuxt/plugin/ui.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser_bsk6z5yxqudsjn47hvdlkzl57m/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/siteConfig.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser_bsk6z5yxqudsjn47hvdlkzl57m/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/inferSeoMetaPlugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-schema-org@3.4.7_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_hmicoss56wvemrfzghdz2kdefy/node_modules/nuxt-schema-org/dist/runtime/app/plugins/i18n/defaults.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0_lvglfye353ngog4vxmsitjupfu/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36.0_lvglfye353ngog4vxmsitjupfu/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_xli7datkpntc2nvw6xaylodxd4/node_modules/@nuxtjs/robots/dist/runtime/nuxt/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5._5kgan4cud4jbkht775nl4u6hqq/node_modules/nuxt-site-config/dist/runtime/nuxt/plugins/i18n.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+content@2.13.4_ioredis@5.4.1_magicast@0.3.5_nuxt@3.14.159_@parcel+watcher@2.5.0_@types+_gumamkqtn27z2ytilwu4wxbpju/node_modules/@nuxt/content/dist/runtime/plugins/ws.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.27.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5_rollup@4.27.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.27.3_vue@3.5.13_typescript@5.6.3_/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@8.5.5_magicast@0.3.5_rollup@4.27.3_vue@3.5.13_typescript@5.6.3_/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.1_eslint@8.57.0_ioredis@5.4.1_magicast@0_fa7dixccytg3463t3lccksbkhm/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser_bsk6z5yxqudsjn47hvdlkzl57m/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/1.absoluteImageUrls.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser_bsk6z5yxqudsjn47hvdlkzl57m/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/0.routeRules.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt-schema-org@3.4.7_magicast@0.3.5_rollup@4.27.3_vite@5.4.11_@types+node@22.9.1_terser@5.36_hmicoss56wvemrfzghdz2kdefy/node_modules/nuxt-schema-org/dist/runtime/app/plugins/i18n/init.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt-seo:fallback-titles' | 'nuxt-seo:defaults' | 'nuxt-schema-org:defaults' | 'nuxt-site-config:i18n' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin' | 'nuxt:checkIfLayoutUsed' | 'nuxt-schema-org:init'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
