/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'app': RouteRecordInfo<'app', '/app', Record<never, never>, Record<never, never>>,
    'app-admin': RouteRecordInfo<'app-admin', '/app/admin', Record<never, never>, Record<never, never>>,
    'app-admin-users': RouteRecordInfo<'app-admin-users', '/app/admin/users', Record<never, never>, Record<never, never>>,
    'app-ai-demo': RouteRecordInfo<'app-ai-demo', '/app/ai-demo', Record<never, never>, Record<never, never>>,
    'app-dashboard': RouteRecordInfo<'app-dashboard', '/app/dashboard', Record<never, never>, Record<never, never>>,
    'app-settings': RouteRecordInfo<'app-settings', '/app/settings', Record<never, never>, Record<never, never>>,
    'app-settings-account-general': RouteRecordInfo<'app-settings-account-general', '/app/settings/account/general', Record<never, never>, Record<never, never>>,
    'app-settings-team-billing': RouteRecordInfo<'app-settings-team-billing', '/app/settings/team/billing', Record<never, never>, Record<never, never>>,
    'app-settings-team-general': RouteRecordInfo<'app-settings-team-general', '/app/settings/team/general', Record<never, never>, Record<never, never>>,
    'app-settings-team-members': RouteRecordInfo<'app-settings-team-members', '/app/settings/team/members', Record<never, never>, Record<never, never>>,
    'auth-forgot-password': RouteRecordInfo<'auth-forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'auth-otp': RouteRecordInfo<'auth-otp', '/auth/otp', Record<never, never>, Record<never, never>>,
    'auth-signup': RouteRecordInfo<'auth-signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    'auth-verify': RouteRecordInfo<'auth-verify', '/auth/verify', Record<never, never>, Record<never, never>>,
    'blog': RouteRecordInfo<'blog', '/blog', Record<never, never>, Record<never, never>>,
    'blog-path': RouteRecordInfo<'blog-path', '/blog/:path()', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    'changelog': RouteRecordInfo<'changelog', '/changelog', Record<never, never>, Record<never, never>>,
    'docs-path': RouteRecordInfo<'docs-path', '/docs/:path(.*)*', { path?: ParamValueZeroOrMore<true> }, { path?: ParamValueZeroOrMore<false> }>,
    'index-back': RouteRecordInfo<'index-back', '/index-back', Record<never, never>, Record<never, never>>,
    'legal-path': RouteRecordInfo<'legal-path', '/legal/:path()', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    'onboarding': RouteRecordInfo<'onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    'pricing': RouteRecordInfo<'pricing', '/pricing', Record<never, never>, Record<never, never>>,
    'team-invitation': RouteRecordInfo<'team-invitation', '/team/invitation', Record<never, never>, Record<never, never>>,
  }
}
